name: Create Keystore

on:
  workflow_dispatch:

jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore
        run: |
          keytool -genkeypair -v \
            -storetype PKCS12 \
            -keystore navasan.keystore \
            -alias navasan \
            -keyalg RSA \
            -keysize 2048 \
            -validity 10000 \
            -storepass Navasan2026 \
            -keypass Navasan2026 \
            -dname "CN=NAVASAN, OU=Trading, O=NAVASAN, L=Tehran, ST=Tehran, C=IR"
          
          echo ""
          echo "=========== COPY FROM HERE ==========="
          base64 -w 0 navasan.keystore
          echo ""
          echo "=========== COPY UNTIL HERE ==========="
          echo ""
          echo "STORE_PASSWORD: Navasan2026"
          echo "KEY_ALIAS: navasan"
          echo "KEY_PASSWORD: Navasan2026"
